package monk

import (
	"time"

	"github.com/wowsims/cata/sim/core"
	"github.com/wowsims/cata/sim/core/proto"
	"github.com/wowsims/cata/sim/core/stats"
)

type Stance uint8

const (
	StanceNone         = 0
	FierceTiger Stance = 1 << iota
	SturdyOx
	WiseSerpent
)

const stanceEffectCategory = "Stance"

func (monk *Monk) StanceMatches(other Stance) bool {
	return (monk.Stance & other) != 0
}

func (monk *Monk) makeStanceSpell(stance Stance, aura *core.Aura, stanceCD *core.Timer) *core.Spell {
	return monk.RegisterSpell(core.SpellConfig{
		ActionID: aura.ActionID,
		Flags:    core.SpellFlagNoOnCastComplete | core.SpellFlagAPL,

		Cast: core.CastConfig{
			CD: core.Cooldown{
				Timer:    stanceCD,
				Duration: time.Second,
			},
		},
		ExtraCastCondition: func(sim *core.Simulation, target *core.Unit) bool {
			return monk.Stance != stance
		},

		ApplyEffects: func(sim *core.Simulation, _ *core.Unit, _ *core.Spell) {
			aura.Activate(sim)
		},
	})
}

func (monk *Monk) registerStanceOfTheSturdyOx(stanceCD *core.Timer) {
	if monk.Spec != proto.Spec_SpecBrewmasterMonk {
		return
	}

	monk.StanceOfTheSturdyOxAura = monk.GetOrRegisterAura(core.Aura{
		Label:    "Stance of the Sturdy Ox",
		ActionID: core.ActionID{SpellID: 115069},
		Duration: core.NeverExpires,
		OnGain: func(aura *core.Aura, sim *core.Simulation) {
			monk.Stance = SturdyOx
			aura.Unit.PseudoStats.DamageTakenMultiplier *= 0.75
			aura.Unit.PseudoStats.ReducedCritTakenChance += 0.06
			aura.Unit.MultiplyEnergyRegenSpeed(sim, 1.1)
		},
		OnExpire: func(aura *core.Aura, sim *core.Simulation) {
			monk.Stance = StanceNone
			aura.Unit.PseudoStats.DamageTakenMultiplier /= 0.75
			aura.Unit.PseudoStats.ReducedCritTakenChance -= 0.06
			aura.Unit.MultiplyEnergyRegenSpeed(sim, 1.0/1.1)
		},
	})

	monk.StanceOfTheSturdyOxAura.NewExclusiveEffect(stanceEffectCategory, true, core.ExclusiveEffect{})
	monk.StanceOfTheSturdyOx = monk.makeStanceSpell(FierceTiger, monk.StanceOfTheSturdyOxAura, stanceCD)
}

func (monk *Monk) registerStanceOfTheWiseSerpent(stanceCD *core.Timer) {
	if monk.Spec != proto.Spec_SpecMistweaverMonk {
		return
	}

	hitDep := monk.NewDynamicStatDependency(stats.Spirit, stats.HitRating, 0.5)
	expDep := monk.NewDynamicStatDependency(stats.Spirit, stats.ExpertiseRating, 0.5)
	hasteDep := monk.NewDynamicMultiplyStat(stats.HasteRating, 1.5)

	monk.StanceOfTheWiseSerpentAura = monk.GetOrRegisterAura(core.Aura{
		Label:    "Stance of the Wise Serpent",
		ActionID: core.ActionID{SpellID: 136336},
		Duration: core.NeverExpires,
		OnGain: func(aura *core.Aura, sim *core.Simulation) {
			// TODO: "Replaces your Energy resource with Mana."
			// TODO: "Your attack power is equal to 200% of your spell power, and you no longer benefit from other sources of attack power."
			// TODO: "In addition, you also gain Eminence, causing you to heal the lowest health nearby target within 20 yards for an amount equal to 25% of non-autoattack damage you deal."
			monk.Stance = WiseSerpent
			aura.Unit.PseudoStats.HealingDealtMultiplier *= 1.2
			aura.Unit.EnableDynamicStatDep(sim, hitDep)
			aura.Unit.EnableDynamicStatDep(sim, expDep)
			aura.Unit.EnableDynamicStatDep(sim, hasteDep)
		},
		OnExpire: func(aura *core.Aura, sim *core.Simulation) {
			monk.Stance = StanceNone
			aura.Unit.PseudoStats.HealingDealtMultiplier /= 1.2
			aura.Unit.DisableDynamicStatDep(sim, hitDep)
			aura.Unit.DisableDynamicStatDep(sim, expDep)
			aura.Unit.DisableDynamicStatDep(sim, hasteDep)
		},
	})

	monk.StanceOfTheWiseSerpentAura.NewExclusiveEffect(stanceEffectCategory, true, core.ExclusiveEffect{})
	monk.StanceOfTheWiseSerpent = monk.makeStanceSpell(FierceTiger, monk.StanceOfTheWiseSerpentAura, stanceCD)
}

/*
Increases your movement speed by 10%, increases damage done by 10% and increases the amount of Chi generated by your Jab and Expel Harm abilities by 1.
*/
func (monk *Monk) registerStanceOfTheFierceTiger(stanceCD *core.Timer) {
	monk.StanceOfTheFierceTigerAura = monk.GetOrRegisterAura(core.Aura{
		Label:    "Stance of the Fierce Tiger",
		ActionID: core.ActionID{SpellID: 103985},
		Duration: core.NeverExpires,
		OnGain: func(aura *core.Aura, sim *core.Simulation) {
			monk.Stance = FierceTiger
			aura.Unit.PseudoStats.DamageDealtMultiplier *= 1.1
			// This **does** stack with other movement speed buffs.
			aura.Unit.PseudoStats.MovementSpeedMultiplier *= 1.1
		},
		OnExpire: func(aura *core.Aura, sim *core.Simulation) {
			monk.Stance = StanceNone
			aura.Unit.PseudoStats.DamageDealtMultiplier /= 1.1
			aura.Unit.PseudoStats.MovementSpeedMultiplier /= 1.1
		},
	})

	monk.StanceOfTheFierceTigerAura.NewExclusiveEffect(stanceEffectCategory, true, core.ExclusiveEffect{})
	monk.StanceOfTheFierceTiger = monk.makeStanceSpell(FierceTiger, monk.StanceOfTheFierceTigerAura, stanceCD)
}

func (monk *Monk) registerStances() {
	stanceCD := monk.NewTimer()
	monk.registerStanceOfTheSturdyOx(stanceCD)
	monk.registerStanceOfTheWiseSerpent(stanceCD)
	monk.registerStanceOfTheFierceTiger(stanceCD)
}
